Upgrade stylelint to 16
convidera/frontend-kit pull request #8
Opened 2024-09-05 12:20 UTC by kalievsky

2024-09-06 06:42 UTC, kalievsky commented on packages/stylelint-config-vue/stylelint.config.js
> +    'scss/load-partial-extension': null,
Not sure. Sometimes we import styles from node_modules by package name only

2024-09-06 10:44 UTC, kalievsky commented on packages/stylelint-config-vue/stylelint.config.js
> +    'scss/load-partial-extension': null,
But it could be imported with ignore comment. And leave this rule globally

2024-09-09 06:07 UTC, deathmaz requested changes
@kalievsky CI is failing, locally I also getting an error when running `yarn install`:
```sh
➤ YN0000: ┌ Resolution step
➤ YN0001: │ Error: @convidera-team/stylelint-config-convidera@npm:^3.0.0: No candidates found
    at ge (/home/maz/projects/frontend-kit/.yarn/releases/yarn-3.5.0.cjs:439:7784)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.allSettled (index 0)
    at async to (/home/maz/projects/frontend-kit/.yarn/releases/yarn-3.5.0.cjs:390:10398)
➤ YN0000: └ Completed in 1s 539ms
➤ YN0000: Failed with errors in 1s 551ms

```

2024-09-09 06:22 UTC, kalievsky commented
Do I maybe need to create dedicated PRs for upgrading of each separate package?

2024-09-09 09:17 UTC, deathmaz commented
> Yep. I need you help for this too. There are upgrades of 2 packages. And second one requires new version of first one
> 
> ```
> "@convidera-team/stylelint-config-convidera": "^3.0.0"
> ```
> 
> But it's not published yet. I did not completely get the publishing rules

There's no need to update packages versions by hand, the versions will be updated by `lerna`, it also will update those versions in all dependent packages

2024-09-09 09:20 UTC, deathmaz approved these changes

2024-09-09 09:21 UTC, merged